apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
    tags.monitoring: dev
    env: dev

resources:
- deployment.yaml
- hpa.yaml
- namespace.yaml
- service.yaml  
- ingress.yaml
