apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: contoh-app-ns


namePrefix: contoh-
commonLabels:
  service_group: contoh-app-group
  service_name: contoh-app

patchesStrategicMerge:
- deployment-patch.yaml
- hpa-patch.yaml
- ingress-patch.yaml
- service-patch.yaml

generators:
- secret-generator.yaml
resources:
- ../../../base
images:
- name: didilmfs/contoh-app
  newTag: main-a60f09be-1673789962
