apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

patchesStrategicMerge:
- sops.yaml
- repo.yaml

resources:
- install.yaml
- application.yaml


generators:
- secret-generator.yaml